### ISSUE TITLE
Make a release on PyPI

### ISSUE THREAD

**Issue by cdeil** [YSOVAR/YSOVAR#13]
A colleague of mine asked me to install `YSOVAR`.
Could you please make a release on PyPI so that `pip install ysovar` works?

**Comment by hamogu** [comment]
It's on testpypi for now:
https://testpypi.python.org/pypi/pYSOVAR/1.0

You can use it already, if it works, but I want to do some more testing to make sure I put all the right files into the distribution before I upload it to the real pypi because this is the first time I ever release stuff to pypi.

**Comment by hamogu** [comment]
https://pypi.python.org/pypi/pYSOVAR/1.0

It's called `pYSOVAR` on pipy, because I wanted to keep the name YSOVAR free for other uses. We really should have called the package pYSOVAR in the first place. Would have been so much cooler...

so 
`pip install pYSOVAR`, but import it with `import YSOVAR`.

**Comment by cdeil** [comment]
Thanks for making the release on PyPI!

My 2 cents (and PEP8 says this also): Python package names should always be lower-case so that users don't have to remember the capitalisation, even if it's an acronym.
